# Generated by Django 3.1.5 on 2021-01-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_auto_20210119_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
